# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=45, unique=True)),
                ('rhyming', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'Rhyme',
                'managed': False,
            },
        ),
    ]
