# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetrify', '0002_rhymegroups_rhymewords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('wordsList', models.CharField(db_column='wordsList', max_length=200)),
                ('rhymes', models.IntegerField()),
            ],
            options={
                'db_table': 'Approval',
                'managed': False,
            },
        ),
    ]
